https_enabled = false
port = 18080
https_port = 18443
site = "http://www.webvpn.info"
num_processes = 1
cache = false
cache_dir = "cache"
public_dir = "../public"
ssl_dir = "../ssl"
intercept_log = false
disable_jump = false
confirm_jump = false
disable_source_map = true
enable_plugins = true
debug = false
disable_devtools = true
rewrite_this = false
domain_mode = "underline"
